services:
    _defaults:
        autowire: true
        autoconfigure: true
    Beer\:
        resource: '../../src/Beer'
        exclude: '../../src/Beer/Entity/'
    Beer\Controller\:
        resource: '../../src/Beer/Controller/'
        tags: ['controller.service_arguments']