doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: '%env(resolve:TENANT_DATABASE_NAME)%'
                host: '%env(resolve:TENANT_DATABASE_HOST)%'
                port: '%env(resolve:TENANT_DATABASE_PORT)%'
                user: '%env(resolve:TENANT_DATABASE_USER)%'
                password: '%env(resolve:TENANT_DATABASE_PASSWORD)%'
                driver: pdo_mysql
                use_savepoints: true
            gerent:
                dbname: '%env(resolve:DATABASE_NAME)%'
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                driver: pdo_mysql
                use_savepoints: true
    orm:
        enable_lazy_ghost_objects: true
        default_entity_manager: tenant_em
        entity_managers:
            tenant_em:
                connection: default
                mappings:
                    User:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/Mapping/tenant'
                        prefix: 'Tenant\User\Domain\Model'
                        alias: Tenant\User\Domain\Model
            gerent_em:
                connection: gerent
                mappings:
                    User:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/Mapping/gerent'
                        prefix: 'Gerent\User\Domain\Model'
                        alias: Gerent\User\Domain\Model

when@test:
    doctrine:
        dbal:
            dbname_suffix: false

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
