version: '3.5'
services:  
    multitenant:
        container_name: multitenant
        build:
            context: .
            args:
                UID: $U_ID
        ports:
            - "${PORT}:80"
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_CLIENT_HOST: 172.17.0.1
            XDEBUG_CLIENT_PORT: 9003
    multitenant-db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: multitenant-db
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - multitenant-data:/var/lib/mysql
volumes:
    multitenant-data: