api_login_check:
    path: /api/login_check

gerent-user-change-password:
    path: /api/gerent/user/{id}/change-password
    controller: App\Controller\ChangePasswordController
    methods: POST

beer-check-healt:
    path: /api/beer/check-healt
    controller: App\Controller\StatusController
    methods: GET