api_login_check:
    path: /api/login_check

gerent-user-change-password:
    path: /api/user/{id}/change-password
    controller: App\Controller\ChangePasswordController
    methods: POST

get-user:
    path: /api/user/list
    controller: App\Controller\ListUserController
    methods: GET