gerent-user-change-password:
    path: /{id}/change-password
    controller: Gerent\User\Adapter\Framework\Controller\ChangePasswordController
    methods: POST

gerent-get-user:
    path: /list
    controller: Gerent\User\Adapter\Framework\Controller\ListUserController
    methods: GET